### ISSUE TITLE
Add tag for 0.7.0

### ISSUE THREAD

**Issue by jocmp** [Tlaster/Swiper#2]
Can you add a tag for `0.7.0` from the master branch so that [Jitpack](https://jitpack.io/#Tlaster/Swiper) will register the latest commit?

**Comment by Tlaster** [comment]
I've just added a tag `0.7.0`, jitpack should have the version `0.7.0` now.

**Comment by jocmp** [comment]
Thanks! There was a build failure but it should be easy to fix: https://github.com/Tlaster/Swiper/pull/3

**Comment by jocmp** [comment]
0.7.1 worked - thanks again.
